name: Lint and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pylint-and-pytest:
    name: Testing and Linting python scripts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint

      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files "*.py") --generated-members torch

      - name: Testing the code with pytest
        run: |
          cd web
          python -m pytest tests -q --disable-warnings
  
  jslint:
    name: ES6 linter
    needs: pylint-and-pytest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prettier Action
        uses: creyD/prettier_action@v4.2
